export const BACK_OFFICE_COPY = {
  adminDesa: {
    common: {
      connectionError: "Koneksi bermasalah. Coba lagi.",
      genericFailed: "Gagal.",
      close: "Tutup",
      cancel: "Batal",
      you: "Kamu",
    },
    documents: {
      headingEyebrow: "Arsip kerja",
      headingTitle: "Dokumen Desa",
      summary: {
        total: "Total",
        waiting: "Menunggu",
        published: "Tayang",
        documents: "dokumen",
      },
      status: {
        WAITING_VERIFIED_APPROVAL: "Menunggu",
        PROCESSING: "Diproses",
        PUBLISHED: "Sudah tayang",
        FAILED: "Gagal",
      },
      upload: {
        eyebrow: "Unggah dokumen",
        title: "Tambah dokumen",
        titleLabel: "Judul dokumen",
        titlePlaceholder: "Contoh: APBDes 2026",
        categoryLabel: "Kategori",
        attachmentLabel: "Lampiran",
        responsibility: "Saya menyatakan dokumen yang diunggah benar dan dapat dipertanggungjawabkan.",
        storageNotConfiguredTitle: "Storage belum terkonfigurasi",
        storageNotConfiguredBody: "Unggah dan preview akan ditolak. Hubungi admin PantauDesa.",
        storageNotReadyShort: "Storage belum siap. Hubungi admin PantauDesa untuk konfigurasi.",
        uploading: "Mengunggah...",
        uploadDocument: "Unggah Dokumen",
        uploadMultipleDocuments: (count: number) => `Unggah ${count} Dokumen`,
        helper: (maxFileSizeMB: number, maxFilesPerUpload: number, formats: string) =>
          `Maks ${maxFileSizeMB} MB/file, ${maxFilesPerUpload} file/unggah. Format: ${formats}.`,
        maxFilesError: (maxFilesPerUpload: number) => `Maksimal ${maxFilesPerUpload} file per unggah.`,
        missingStorageDetail: (env: string) => `Env belum diisi: ${env}.`,
        invalidStorageDetail: (env: string) => `Format env tidak valid: ${env}.`,
        storageNotReady: (detail: string) => `Storage belum siap. ${detail}`,
        chooseFileError: "Pilih minimal satu file.",
        responsibilityError: "Centang pernyataan tanggung jawab sebelum unggah.",
        fileTooLargeError: (fileName: string, maxFileSizeMB: number) => `"${fileName}" melebihi batas ${maxFileSizeMB} MB.`,
        fileTypeError: (fileName: string) => `"${fileName}": tipe file tidak diizinkan.`,
        uploadFailed: "Gagal mengunggah.",
        serverNoConfirmation: "Server tidak mengembalikan konfirmasi. Coba refresh lalu cek daftar dokumen.",
        uploadSuccess: (count: number) => `${count} dokumen berhasil diunggah.`,
      },
      list: {
        title: "Daftar dokumen",
        empty: "Belum ada dokumen.",
      },
      failedReasonLabel: "Alasan:",
      actions: {
        preview: "Preview",
        approve: "Setujui",
        forwardedToPantauDesa: "Dokumen diteruskan ke PantauDesa.",
      },
    },
    listAdmin: {
      headingEyebrow: "Kelola anggota",
      headingTitle: "Tim Admin Desa",
      inviteButton: "Undang Admin",
      summary: {
        active: "Admin aktif",
        verified: "Verified",
        limited: "Terbatas",
        invites: "Undangan",
      },
      roleStatus: {
        VERIFIED: "Admin terverifikasi",
        LIMITED: "Admin terbatas",
        REVOKED: "Akses dicabut",
        EXPIRED: "Masa aktif berakhir",
      },
      notices: {
        onlyMainAdminCanManage: "Hanya admin utama desa yang dapat mengundang atau mencabut akses admin lain.",
        inviteLimitReached: (maxAdmins: number) =>
          `Batas ${maxAdmins} admin aktif sudah tercapai. Cabut salah satu admin terbatas jika ingin membuka slot baru.`,
      },
      activeSection: {
        eyebrow: "Anggota aktif",
        title: "Struktur tim yang sedang bekerja",
        empty: "Belum ada admin aktif.",
      },
      inviteSection: {
        eyebrow: "Undangan",
        title: "Undangan yang masih menunggu",
        expired: "Sudah kedaluwarsa",
        pending: "Pending",
        expiredShort: "Expired",
        validUntil: (date: string) => `Berlaku sampai ${date}`,
        sentAt: (date: string) => `Dikirim ${date}`,
      },
      historySection: {
        eyebrow: "Riwayat",
        title: "Akses yang sudah berakhir",
        revokedWithReason: (date: string, reason: string) => `Dicabut pada ${date} karena ${reason}`,
      },
      modal: {
        eyebrow: "Aksi admin",
        inviteTitle: "Undang Admin Desa",
        inviteSubtitle: (desaName: string) => `Undangan baru untuk ${desaName}`,
        inviteNotice: "Undangan ini memberi akses awal sebagai admin terbatas. Setelah itu, pengguna tetap perlu melalui verifikasi lanjutan.",
        inviteEmailLabel: "Email invitee",
        inviteEmailPlaceholder: "email@desa.id",
        inviteHelper: "Sistem akan memblokir undangan jika email ini sudah aktif sebagai Admin Desa di desa lain.",
        sendInvite: "Kirim Undangan",
        sendingInvite: "Mengirim...",
        inviteSuccess: "Undangan berhasil dikirim. Calon admin akan menerima tautan untuk menerima undangan.",
        inviteFailed: "Gagal mengirim undangan.",
        emailRequired: "Email wajib diisi.",
        revokeTitle: "Cabut akses admin",
        revokeNotice: "Akses akan diubah menjadi REVOKED. Riwayat audit dan dokumen yang pernah diunggah tetap tersimpan.",
        revokeReasonLabel: "Alasan pencabutan",
        revokeReasonPlaceholder: "Contoh: Tidak lagi bertugas sebagai pengelola data desa.",
        revokeButton: "Hapus Akses",
        revokeLoading: "Memproses...",
        revokeSuccess: "Akses admin berhasil dicabut.",
        revokeFailed: "Gagal mencabut akses.",
      },
      actions: {
        revokeAriaLabel: (name: string) => `Hapus akses ${name}`,
      },
    },
    notifications: {
      summary: {
        total: "Total",
        unread: "Belum baca",
      },
      actions: {
        markAllRead: "Tandai semua baca",
        markOneRead: "Baca",
      },
      messages: {
        markAllReadSuccess: "Semua notifikasi ditandai dibaca.",
        markAllReadFailed: "Gagal.",
        markOneReadSuccess: "Notifikasi ditandai dibaca.",
        markOneReadFailed: "Gagal.",
      },
      empty: "Belum ada notifikasi.",
      newBadge: "Baru",
    },
  },
  internalAdmin: {
    common: {},
  },
  user: {
    common: {},
  },
} as const;

export type BackOfficeCopy = typeof BACK_OFFICE_COPY;
