// Canonical audit event type constants for admin claim actions.
// All event types are string literals for DB storage flexibility.

export const AUDIT_EVENT = {
  // Claim lifecycle
  CLAIM_STARTED:          "CLAIM_STARTED",
  CLAIM_REUSED:           "CLAIM_REUSED",
  CLAIM_METHOD_UPDATED:   "CLAIM_METHOD_UPDATED",

  // Email verification
  EMAIL_TOKEN_GENERATED:  "EMAIL_TOKEN_GENERATED",
  EMAIL_TOKEN_VERIFIED:   "EMAIL_TOKEN_VERIFIED",
  EMAIL_TOKEN_EXPIRED:    "EMAIL_TOKEN_EXPIRED",
  EMAIL_TOKEN_INVALID:    "EMAIL_TOKEN_INVALID",

  // Website token
  WEBSITE_TOKEN_GENERATED: "WEBSITE_TOKEN_GENERATED",
  WEBSITE_TOKEN_FOUND:     "WEBSITE_TOKEN_FOUND",
  WEBSITE_TOKEN_NOT_FOUND: "WEBSITE_TOKEN_NOT_FOUND",
  WEBSITE_TOKEN_EXPIRED:   "WEBSITE_TOKEN_EXPIRED",
  WEBSITE_CHECK_BLOCKED:   "WEBSITE_CHECK_BLOCKED",

  // Status transitions
  STATUS_TO_LIMITED:      "STATUS_TO_LIMITED",
  STATUS_TO_VERIFIED:     "STATUS_TO_VERIFIED",
  STATUS_TO_REJECTED:     "STATUS_TO_REJECTED",
  STATUS_TO_SUSPENDED:    "STATUS_TO_SUSPENDED",

  // Invite
  INVITE_CREATED:         "INVITE_CREATED",
  INVITE_ACCEPTED:        "INVITE_ACCEPTED",
  INVITE_EXPIRED:         "INVITE_EXPIRED",

  // Fake report
  FAKE_ADMIN_REPORT_SUBMITTED: "FAKE_ADMIN_REPORT_SUBMITTED",
  ADMIN_CLAIM_FLAGGED_BY_PUBLIC: "ADMIN_CLAIM_FLAGGED_BY_PUBLIC",
} as const;

export type AuditEventType = typeof AUDIT_EVENT[keyof typeof AUDIT_EVENT];
